version: '3.5'

services:
    api:
    build: .
    container_name: test_api
    restart: always
    ports:
      - 80:80
    networks:
      api_net:
        aliases:
          - "test_api"
    working_dir: /app

networks:
  api_net:
    driver: bridge
